### ISSUE TITLE
eslint 설정 분리 및 일부 rule 수정

### ISSUE THREAD

**Issue by skyoo2003** [itslaves/rentalgames-front#7]
### To-do List
- [x] package.json 에 있던 eslint 설정을 외부로 분리
- [x] no-empty 룰 off

**Comment by hayden-han** [comment]
오잉?? 이거 develop에 바로 작업하신건가??

**Comment by skyoo2003** [comment]
@haninkyu 

오 넵! 미팅때 이야기한 내용에서 추가된 내용이 없어서 바로 반영했는데, PR을 통해서 머지하는걸 깜빡했군여 ㅈㅅㅈㅅ
